apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: "operator-metering"
  namespace: "openshift-metering"
spec:
  reporting-operator:
    spec:
      nodeSelector:
        "node-role.kubernetes.io/infra": "" 

  presto:
    spec:
      coordinator:
        nodeSelector:
          "node-role.kubernetes.io/infra": "" 
      worker:
        nodeSelector:
          "node-role.kubernetes.io/infra": "" 
  hive:
    spec:
      metastore:
        nodeSelector:
          "node-role.kubernetes.io/infra": "" 
      server:
        nodeSelector:
          "node-role.kubernetes.io/infra": "" 
  storage:
    type: "hive"
    hive:
      type: "sharedPVC"
      sharedPVC:
        claimName: "metering-nfs" 
        # Uncomment the lines below to provision a new PVC using the specified storageClass. 
        # createPVC: true
        # storageClass: "my-nfs-storage-class"
        # size: 5Gi
