apiVersion: config.openshift.io/v1
kind: Scheduler
metadata:
  name: cluster
spec:
  # Place application workloads on app nodes
  defaultNodeSelector: node-role.kubernetes.io/app=
  # Do not place any workloads on master nodes
  mastersSchedulable: false
