# Mark the node as infra node by attaching the infra label to it.
# Remove the default worker label from the infra node.
apiVersion: v1
kind: Node
metadata:
  labels:
    node-role.kubernetes.io/worker: null
    node-role.kubernetes.io/infra: ""
  name: infra2
